#
# @lucastrvsn zsh config
# adapted from prezto (https://github.com/sorin-ionescu/prezto)
#

# source all configurations inside ~/.config/zsh/*
CONFIGS=(
  plugins
  homebrew
  asdf
  jobs
  directory
  history
  completion
  vi
  aliases
  prompt
)

for config in $CONFIGS; do
  source $HOME/.config/zsh/$config end
done

# vim: ft=zsh
